force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <label>Physician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Specialization</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <inlineHelpText>This shows the Fee per appointment</inlineHelpText>
    <label>Appointment Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Utility.cls
public with sharing class Utility {
@AuraEnabled(cacheable=true)
public static Map<String,Specialization__c> getSpecializations() {
    Map<String,Specialization__c> specializationList = new Map<String,Specialization__c>();
   for (Specialization__c spec : [SELECT Name,Price__c FROM Specialization__c ]){
    specializationList.put(spec.Name, spec);
   }
   return specializationList;
 }

 @AuraEnabled(cacheable=true)
public static List<Physician__c> getPhysiciansbySpecialization(String name) {
    List<Physician__c> physicianList = new List<Physician__c>();
   for (Physician__c physician : [SELECT Name,Email__c,Summary__c FROM Physician__c where Specialization__r.Name =:name and Summary__c != null
                                  and Summary__c != '']){
    physicianList.add(physician);
   }
   return physicianList;
 }
}